[project]
name = "beijing_fushengji_rewrite"
version = "0.1.0"
description = "beijing fushengji (a simple simulation game) rewritten in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.10.0",
    "pyside6>=6.6.3.1",
]

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]
"ui/*.py" = ["F401"]
"tests/*.py" = ["E402", "F401"]
